"""add two columns

Revision ID: 1c92f8abc1ef
Revises: ecf4748145f2
Create Date: 2026-03-22 09:59:35.522861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c92f8abc1ef'
down_revision: Union[str, Sequence[str], None] = 'ecf4748145f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advisory_requests', sa.Column('image_b64', sa.Text(), nullable=True))
    op.add_column('advisory_requests', sa.Column('image_media_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advisory_requests', 'image_media_type')
    op.drop_column('advisory_requests', 'image_b64')
    # ### end Alembic commands ###
