"""create advisory_requests table

Revision ID: 3df03fdda3ee
Revises: 996bcccf109b
Create Date: 2026-03-18 15:58:59.730084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df03fdda3ee'
down_revision: Union[str, Sequence[str], None] = '996bcccf109b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisory_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_phone', sa.String(length=20), nullable=False),
    sa.Column('message_id', sa.String(length=100), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='advisorystatus'), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advisory_requests')
    # ### end Alembic commands ###
