"""add indexes and detections table

Revision ID: cec474569e17
Revises: 1c92f8abc1ef
Create Date: 2026-03-22 20:50:50.611067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cec474569e17'
down_revision: Union[str, Sequence[str], None] = '1c92f8abc1ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('advisory_request_id', sa.UUID(), nullable=True),
    sa.Column('farmer_phone', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('image_media_type', sa.String(length=50), nullable=False),
    sa.Column('predicted_class', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('has_disease', sa.Boolean(), nullable=True),
    sa.Column('raw_diagnosis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('treatment_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['advisory_request_id'], ['advisory_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['farmer_phone'], ['farmers.phone_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_detections_created_at', 'detections', ['created_at'], unique=False)
    op.create_index('ix_detections_farmer_phone', 'detections', ['farmer_phone'], unique=False)
    op.create_index('ix_detections_predicted_class', 'detections', ['predicted_class'], unique=False)
    op.create_index('ix_advisory_created_at', 'advisory_requests', ['created_at'], unique=False)
    op.create_index('ix_advisory_farmer_phone', 'advisory_requests', ['farmer_phone'], unique=False)
    op.create_index('ix_advisory_farmer_phone_status', 'advisory_requests', ['farmer_phone', 'status'], unique=False)
    op.create_index('ix_advisory_status', 'advisory_requests', ['status'], unique=False)
    op.create_index('ix_advisory_status_updated_at', 'advisory_requests', ['status', 'updated_at'], unique=False)
    op.create_foreign_key(None, 'advisory_requests', 'farmers', ['farmer_phone'], ['phone_number'], ondelete='CASCADE')
    op.create_index('ix_farmers_district', 'farmers', ['district'], unique=False)
    op.create_index('ix_farmers_is_active', 'farmers', ['is_active'], unique=False)
    op.create_index('ix_fields_farmer_phone', 'fields', ['farmer_phone'], unique=False)
    op.create_index('ix_fields_farmer_phone_active', 'fields', ['farmer_phone', 'is_active'], unique=False)
    op.create_index('ix_fields_lat_lng', 'fields', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_fields_ndvi_score', 'fields', ['ndvi_score'], unique=False)
    op.drop_constraint(op.f('fields_farmer_phone_fkey'), 'fields', type_='foreignkey')
    op.create_foreign_key(None, 'fields', 'farmers', ['farmer_phone'], ['phone_number'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fields', type_='foreignkey')
    op.create_foreign_key(op.f('fields_farmer_phone_fkey'), 'fields', 'farmers', ['farmer_phone'], ['phone_number'])
    op.drop_index('ix_fields_ndvi_score', table_name='fields')
    op.drop_index('ix_fields_lat_lng', table_name='fields')
    op.drop_index('ix_fields_farmer_phone_active', table_name='fields')
    op.drop_index('ix_fields_farmer_phone', table_name='fields')
    op.drop_index('ix_farmers_is_active', table_name='farmers')
    op.drop_index('ix_farmers_district', table_name='farmers')
    op.drop_constraint(None, 'advisory_requests', type_='foreignkey')
    op.drop_index('ix_advisory_status_updated_at', table_name='advisory_requests')
    op.drop_index('ix_advisory_status', table_name='advisory_requests')
    op.drop_index('ix_advisory_farmer_phone_status', table_name='advisory_requests')
    op.drop_index('ix_advisory_farmer_phone', table_name='advisory_requests')
    op.drop_index('ix_advisory_created_at', table_name='advisory_requests')
    op.drop_index('ix_detections_predicted_class', table_name='detections')
    op.drop_index('ix_detections_farmer_phone', table_name='detections')
    op.drop_index('ix_detections_created_at', table_name='detections')
    op.drop_table('detections')
    # ### end Alembic commands ###
