"""create fields table

Revision ID: d44db58b8ab5
Revises: 3df03fdda3ee
Create Date: 2026-03-18 16:55:52.857073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd44db58b8ab5'
down_revision: Union[str, Sequence[str], None] = '3df03fdda3ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('crop_type', sa.String(length=50), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('soil_type', sa.String(length=50), nullable=True),
    sa.Column('irrigation_method', sa.String(length=50), nullable=True),
    sa.Column('ndvi_score', sa.Float(), nullable=True),
    sa.Column('ndvi_updated_at', sa.DateTime(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_phone'], ['farmers.phone_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fields')
    # ### end Alembic commands ###
