# app/models/detection.py
"""
Standalone disease detection record.
Separate from AdvisoryRequest so detection results are
first-class objects that can be queried independently.
"""

import uuid
from datetime import datetime
from sqlalchemy import String, DateTime, Float, Text, ForeignKey, Index, Boolean
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.models import Base
from app.models.farmer import Farmer


class Detection(Base):
    __tablename__ = "detections"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    # Linked to the advisory request that triggered this detection
    advisory_request_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("advisory_requests.id", ondelete="SET NULL"),
        nullable=True,
    )
    farmer_phone: Mapped[str] = mapped_column(
        String(20),
        ForeignKey("farmers.phone_number", ondelete="CASCADE"),
        nullable=False,
    )
    # Image stored in object storage (S3/Azure Blob) — NOT base64 in DB
    image_url: Mapped[str] = mapped_column(Text, nullable=False)
    image_media_type: Mapped[str] = mapped_column(String(50), default="image/jpeg")

    # CNN / vision model output
    predicted_class: Mapped[str | None] = mapped_column(String(100))
    confidence: Mapped[float | None] = mapped_column(Float)
    severity: Mapped[str | None] = mapped_column(String(20))  # none/mild/moderate/severe
    has_disease: Mapped[bool | None] = mapped_column(Boolean)

    # Full JSON payload from vision model
    raw_diagnosis: Mapped[dict | None] = mapped_column(JSONB)
    # Structured treatment plan generated by advisory agent
    treatment_plan: Mapped[dict | None] = mapped_column(JSONB)

    channel: Mapped[str] = mapped_column(String(20), default="web")  # web | whatsapp
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    # Relationships
    farmer: Mapped["Farmer"] = relationship("Farmer", foreign_keys=[farmer_phone])  # noqa: F821

    __table_args__ = (
        Index("ix_detections_farmer_phone", "farmer_phone"),
        Index("ix_detections_created_at", "created_at"),
        Index("ix_detections_predicted_class", "predicted_class"),
    )

    def __repr__(self):
        return f"<Detection {self.predicted_class} ({self.confidence:.2f}) for {self.farmer_phone}>"